# Generated by Django 2.2.1 on 2019-05-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.CharField(choices=[('F', 'Física'), ('J', 'Jurídica')], default='F', max_length=1)),
                ('nome', models.CharField(default='', max_length=50)),
                ('cpf', models.CharField(default='', max_length=11)),
                ('idade', models.PositiveIntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('X', 'Não informado')], default='X', max_length=1)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=25)),
                ('telefone2', models.CharField(blank=True, max_length=25)),
            ],
        ),
    ]
