# Generated by Django 2.2.1 on 2019-05-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao', models.CharField(choices=[('V', 'Venda'), ('L', 'Locação')], default='V', max_length=1)),
                ('finalidade', models.CharField(choices=[('R', 'Residencial'), ('C', 'Comercial')], default='R', max_length=1)),
                ('valor_condominio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('valor_iptu', models.DecimalField(decimal_places=2, max_digits=9)),
                ('garagem', models.PositiveIntegerField()),
                ('tipo_garagem', models.CharField(choices=[('C', 'Coberta'), ('D', 'Descoberta'), ('P', 'Parcial')], default='C', max_length=1)),
                ('dormitorios', models.PositiveIntegerField()),
                ('sendo_suite', models.PositiveIntegerField()),
                ('banheiros', models.PositiveIntegerField()),
                ('face', models.CharField(choices=[('SOM', 'Sombra'), ('SOL', 'Sol')], default='SOM', max_length=3)),
                ('area_terreno', models.DecimalField(decimal_places=2, max_digits=9)),
                ('area_construida', models.DecimalField(decimal_places=2, max_digits=9)),
                ('frente', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fundo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('esquerda', models.DecimalField(decimal_places=2, max_digits=9)),
                ('direita', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
