# Generated by Django 2.2.1 on 2019-05-31 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_auto_20190523_1115'),
        ('imoveis', '0002_auto_20190523_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visita', models.DateTimeField()),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('imovel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='imoveis.Imovel')),
            ],
        ),
    ]
