# Generated by Django 2.2.1 on 2019-05-31 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20190531_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='data_visita',
            field=models.DateField(),
        ),
    ]
