# Generated by Django 2.2.1 on 2019-05-31 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20190531_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='hora_visita',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
